### ISSUE TITLE
http://ww38.nicolacastellani.devplaygrounds.org/ is available for purchase.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [NicolaLC/nica-os#43]

**Comment by RokeJulianLockhart** [comment]
@NicolaLC, how is this complete? The readMe is at the same commit still. Do you want me to propose a PR to remove the URI?

**Comment by NicolaLC** [comment]
@RokeJulianLockhart you are right sorry, I misunderstood your request, I've updated the readme as requested.

Anything I can help you with?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/NicolaLC/nica-os/issues/43#issuecomment-2260707557

@NicolaLC, that's all. Thanks.
